# Build settings
markdown: kramdown
permalink: pretty
safe: true
# debugmode: true
# Use {{ jekyll.environment }} from: https://github.com/jekyll/jekyll/issues/1219#issuecomment-50814813

exclude: ["git-untracked"]

defaults:
  -
    scope:
      path: "pages" # an empty string here means all files in the project
    values:
      section-group: "secondary"
      layout: "default"

# Site settings
title: basimilch
description: Genossenschaft basimilch - Die kooperative Käserei in Dietikon
baseurl: ""
url: "http://basimil.ch"

info:
    name: Genossenschaft basimilch
    shortname: basimilch
    subtitle: Die kooperative Käserei in Dietikon
    email: info@basimil.ch
    address:
        street: Alte Kindhauserstrasse 3
        plz: 8953
        city: Dietikon ZH
        url: https://www.google.ch/maps/place/Alte+Kindhauserstrasse+3+8953+Dietikon+Switzerland

# Consider using site.github hash
# SOURCE: https://github.com/benbalter/benbalter.github.com/blob/14c1d3e597125cf24a71ba4183d7c3f118733cad/_includes/improve.html#L7
# DOC: https://help.github.com/articles/repository-metadata-on-github-pages/#available-repository-metadata
#      https://help.github.com/articles/using-jekyll-with-pages/#defaults
github:
    repo:
        branch: master
        url: https://github.com/basimilch/basimilch.github.io

kramdown:
  # Source for German quote codes: http://symbolcodes.tlt.psu.edu/bylanguage/german.html
  smart_quotes: sbquo,lsquo,bdquo,ldquo

sass:
    style: compressed

# Source: https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  # profile: true
  # ignore:
  #   envs: [local]
